# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-09 15:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import opal.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('opal', '0034_auto_20171214_1845'),
        ('epidurio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EpiduralRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('consistency_token', models.CharField(max_length=8)),
                ('epidural_status', models.IntegerField(help_text='Internal field for managing the state of the epidural request - ordered, in progress, completed, attempted-failed, etc)', null=True)),
                ('history', models.TextField(help_text='Focused summary of the relevant history. Use this area to let the amaesthetist know about any relevant hazards ar special circumstances', null=True)),
                ('cannula_in_situ', models.BooleanField(help_text='Does the patient have a peripheral venous cannula in situ?')),
                ('anticoagulants', models.BooleanField(help_text="Is the patient currently taking anticolagulants, antiplatelet agents, or any other medication that 'thins' blood or affects coagulation?")),
                ('pyrexia', models.BooleanField(help_text='Does the patient have a recent history of pyrexia?')),
                ('hypertension', models.BooleanField(help_text='Does the patient have pregnancy-induced hypertension (PIH)?')),
                ('platelet_count', models.CharField(help_text="Patient's latest Platelet count", max_length=20, null=True)),
                ('request_date_time', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time of the epidural request', null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_epidurio_epiduralrequest_subrecords', to=settings.AUTH_USER_MODEL)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opal.Episode')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_epidurio_epiduralrequest_subrecords', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(opal.models.UpdatesFromDictMixin, opal.models.ToDictMixin, models.Model),
        ),
    ]
