# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-09 16:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import opal.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('opal', '0034_auto_20171214_1845'),
        ('epidurio', '0002_epiduralrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='EpiduralInsertion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('consistency_token', models.CharField(max_length=8)),
                ('insertion_date_time', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time of the epidural insertion or epidural insertion attempt', null=True)),
                ('insertion_record', models.TextField(help_text='Free text clinical record of the intervention', max_length=255, null=True)),
                ('indication', models.CharField(help_text='Description of the intervention', max_length=255, null=True)),
                ('number_of_attempts', models.PositiveIntegerField(default=1, help_text='The number of discrete epidural insertion attempts')),
                ('complications', models.CharField(blank=True, help_text='Complications caused by the epidural insertion', max_length=255, null=True)),
                ('outcome', models.CharField(blank=True, choices=[('SUCCESS', 'Successful epidural insertion and effective analgesia'), ('INEFFECTIVE', 'Successful insertion of epidural catheter'), ('DURAL PUNCTURE', 'Epidural insertion caused dural puncture'), ('FAILURE', 'Failed epidural insertion')], help_text='Outcome of the epidural insertion attempt', max_length=255, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_epidurio_epiduralinsertion_subrecords', to=settings.AUTH_USER_MODEL)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opal.Episode')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_epidurio_epiduralinsertion_subrecords', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(opal.models.UpdatesFromDictMixin, opal.models.ToDictMixin, models.Model),
        ),
        migrations.AlterField(
            model_name='epiduralrequest',
            name='epidural_status',
            field=models.PositiveIntegerField(help_text='Internal field for managing the state of the epidural request - ordered, in progress, completed, attempted-failed, etc)', null=True),
        ),
        migrations.AlterField(
            model_name='epiduralrequest',
            name='request_date_time',
            field=models.DateTimeField(help_text='Date and time of the epidural request', null=True),
        ),
    ]
