# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-09 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epidurio', '0003_auto_20180209_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epiduralinsertion',
            name='insertion_date_time',
            field=models.DateTimeField(help_text='Date and time of the epidural insertion or epidural insertion attempt', null=True),
        ),
    ]
