# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-15 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epidurio', '0004_auto_20180209_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epiduralinsertion',
            name='outcome',
            field=models.CharField(blank=True, choices=[(b'Successful epidural insertion and effective analgesia', b'Successful epidural insertion and effective analgesia'), (b'Successful insertion of epidural catheter', b'Successful insertion of epidural catheter'), (b'Epidural insertion caused dural puncture', b'Epidural insertion caused dural puncture'), (b'Failed epidural insertion', b'Failed epidural insertion')], help_text=b'Outcome of the epidural insertion attempt', max_length=255, null=True),
        ),
    ]
