# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-15 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epidurio', '0005_auto_20180215_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epiduralrequest',
            name='anticoagulants',
            field=models.BooleanField(default=False, help_text=b"Is the patient currently taking anticolagulants, antiplatelet agents, or any other medication that 'thins' blood or affects coagulation?"),
        ),
        migrations.AlterField(
            model_name='epiduralrequest',
            name='cannula_in_situ',
            field=models.BooleanField(default=False, help_text=b'Does the patient have a peripheral venous cannula in situ?'),
        ),
        migrations.AlterField(
            model_name='epiduralrequest',
            name='hypertension',
            field=models.BooleanField(default=False, help_text=b'Does the patient have pregnancy-induced hypertension (PIH)?'),
        ),
        migrations.AlterField(
            model_name='epiduralrequest',
            name='pyrexia',
            field=models.BooleanField(default=False, help_text=b'Does the patient have a recent history of pyrexia?'),
        ),
    ]
