# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-15 14:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import opal.models


class Migration(migrations.Migration):

    dependencies = [
        ('opal', '0034_auto_20171214_1845'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('epidurio', '0006_auto_20180215_1157'),
    ]

    operations = [
        migrations.CreateModel(
            name='EpiduralFollowUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('consistency_token', models.CharField(max_length=8)),
                ('headache', models.BooleanField(default=False)),
                ('has_not_mobilised', models.BooleanField(default=False)),
                ('weakness', models.BooleanField(default=False)),
                ('sensory_disturbance', models.BooleanField(default=False)),
                ('back_pain', models.BooleanField(default=False)),
                ('has_not_passed_urine', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_epidurio_epiduralfollowup_subrecords', to=settings.AUTH_USER_MODEL)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opal.Episode')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_epidurio_epiduralfollowup_subrecords', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(opal.models.UpdatesFromDictMixin, opal.models.ToDictMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SatisfactionRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('consistency_token', models.CharField(max_length=8)),
                ('labor_analgesia', models.CharField(blank=True, choices=[('Dissatisfied', 'Dissatisfied'), ('Satisfied', 'Satisfied'), ('Very Satisfied', 'Very Satisfied')], max_length=255, null=True)),
                ('delivery_analgesia', models.CharField(blank=True, choices=[('Dissatisfied', 'Dissatisfied'), ('Satisfied', 'Satisfied'), ('Very Satisfied', 'Very Satisfied')], max_length=255, null=True)),
                ('post_natal_analgesia', models.CharField(blank=True, choices=[('Dissatisfied', 'Dissatisfied'), ('Satisfied', 'Satisfied'), ('Very Satisfied', 'Very Satisfied')], max_length=255, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_epidurio_satisfactionrating_subrecords', to=settings.AUTH_USER_MODEL)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opal.Episode')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_epidurio_satisfactionrating_subrecords', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(opal.models.UpdatesFromDictMixin, opal.models.ToDictMixin, models.Model),
        ),
        migrations.AlterField(
            model_name='epiduralinsertion',
            name='outcome',
            field=models.CharField(blank=True, choices=[('Successful epidural insertion and effective analgesia', 'Successful epidural insertion and effective analgesia'), ('Successful insertion of epidural catheter', 'Successful insertion of epidural catheter'), ('Epidural insertion caused dural puncture', 'Epidural insertion caused dural puncture'), ('Failed epidural insertion', 'Failed epidural insertion')], help_text='Outcome of the epidural insertion attempt', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='epiduralrequest',
            name='anticoagulants',
            field=models.BooleanField(default=False, help_text="Is the patient currently taking anticolagulants, antiplatelet agents, or any other medication that 'thins' blood or affects coagulation?"),
        ),
        migrations.AlterField(
            model_name='epiduralrequest',
            name='cannula_in_situ',
            field=models.BooleanField(default=False, help_text='Does the patient have a peripheral venous cannula in situ?'),
        ),
        migrations.AlterField(
            model_name='epiduralrequest',
            name='hypertension',
            field=models.BooleanField(default=False, help_text='Does the patient have pregnancy-induced hypertension (PIH)?'),
        ),
        migrations.AlterField(
            model_name='epiduralrequest',
            name='pyrexia',
            field=models.BooleanField(default=False, help_text='Does the patient have a recent history of pyrexia?'),
        ),
    ]
