# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-15 15:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epidurio', '0007_auto_20180215_1432'),
        ('epidurio', '0005_auto_20180213_1718'),
    ]

    operations = [
    ]
