# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-15 15:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epidurio', '0008_merge_20180215_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='epiduralinsertion',
            name='insertion_record_fk',
        ),
        migrations.RemoveField(
            model_name='epiduralinsertion',
            name='insertion_record_ft',
        ),
    ]
