# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-15 15:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epidurio', '0009_auto_20180215_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='epiduralinsertion',
            name='insertion_record_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='epidurio.ProcedureType'),
        ),
        migrations.AddField(
            model_name='epiduralinsertion',
            name='insertion_record_ft',
            field=models.CharField(blank=True, default=b'', max_length=255, null=True),
        ),
    ]
