# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-15 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epidurio', '0010_auto_20180215_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='epiduralfollowup',
            name='time_of_follow_up',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
