# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-16 16:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epidurio', '0011_epiduralfollowup_time_of_follow_up'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='epiduralinsertion',
            name='indication',
        ),
        migrations.AddField(
            model_name='epiduralinsertion',
            name='indication_ft',
            field=models.CharField(blank=True, default=b'', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='epiduralinsertion',
            name='indication_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='epidurio.Indication'),
        ),
    ]
