# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-20 11:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import opal.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('opal', '0034_auto_20171214_1845'),
        ('epidurio', '0015_auto_20180219_1251'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('consistency_token', models.CharField(max_length=8)),
                ('failure', models.BooleanField(default=True)),
                ('analgesia_expectations', models.BooleanField(default=True)),
                ('shivering', models.BooleanField(default=True)),
                ('pruritus', models.BooleanField(default=True)),
                ('blood_pressure_drop', models.BooleanField(default=True)),
                ('nausea_and_vomiting', models.BooleanField(default=True)),
                ('motor_block', models.BooleanField(default=True)),
                ('delayed_second_stage', models.BooleanField(default=True)),
                ('instrumental_delivery', models.BooleanField(default=True)),
                ('headache', models.BooleanField(default=True)),
                ('temporary_nerve_damage', models.BooleanField(default=True)),
                ('permanent_nerve_damage', models.BooleanField(default=True)),
                ('severe_complication', models.BooleanField(default=True)),
                ('other', models.TextField(null=True)),
                ('number_of_attempts', models.PositiveIntegerField(default=1, help_text='The number of discrete epidural insertion attempts')),
                ('complications', models.CharField(blank=True, help_text='Complications caused by the epidural insertion', max_length=255, null=True)),
                ('outcome', models.CharField(blank=True, choices=[('Successful epidural insertion and effective analgesia', 'Successful epidural insertion and effective analgesia'), ('Successful insertion of epidural catheter', 'Successful insertion of epidural catheter'), ('Epidural insertion caused dural puncture', 'Epidural insertion caused dural puncture'), ('Failed epidural insertion', 'Failed epidural insertion')], help_text='Outcome of the epidural insertion attempt', max_length=255, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_epidurio_consent_subrecords', to=settings.AUTH_USER_MODEL)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opal.Episode')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_epidurio_consent_subrecords', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(opal.models.UpdatesFromDictMixin, opal.models.ToDictMixin, models.Model),
        ),
        migrations.RemoveField(
            model_name='epiduralinsertion',
            name='complications',
        ),
        migrations.RemoveField(
            model_name='epiduralinsertion',
            name='number_of_attempts',
        ),
        migrations.RemoveField(
            model_name='epiduralinsertion',
            name='outcome',
        ),
    ]
