# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-20 13:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import opal.models


class Migration(migrations.Migration):

    dependencies = [
        ('opal', '0034_auto_20171214_1845'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('epidurio', '0017_auto_20180220_1110'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technique',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('consistency_token', models.CharField(max_length=8)),
                ('patient_position', models.CharField(blank=True, choices=[('Sitting', 'Sitting'), ('Lateral', 'Lateral')], max_length=255, null=True)),
                ('level', models.CharField(blank=True, choices=[('L2/3', 'L2/3'), ('L3/4', 'L3/4'), ('L3/4', 'L3/4'), ('L4/5', 'L4/5')], max_length=255, null=True)),
                ('approach', models.CharField(blank=True, choices=[('Midline', 'Midline'), ('Paramedian', 'Paramedian')], max_length=255, null=True)),
                ('lidocaine', models.CharField(blank=True, choices=[('1 %', '1 %'), ('2 %', '2 %')], max_length=255, null=True)),
                ('lidocaine_volume', models.PositiveIntegerField(default=3)),
                ('tuohy_needle_choices', models.CharField(blank=True, choices=[('16G', '16G'), ('18G', '18G')], max_length=255, null=True)),
                ('spinal_needle_choices', models.CharField(blank=True, choices=[('26G', '26G'), ('27G', '27G')], max_length=255, null=True)),
                ('loss_of_resistance', models.CharField(blank=True, choices=[('Saline', 'Saline'), ('Air', 'Air')], max_length=255, null=True)),
                ('depth_of_epidural_space', models.PositiveIntegerField(default=3)),
                ('catheter_length_in_epidural_space', models.CharField(blank=True, choices=[('2 cm', '2 cm'), ('3 cm', '3 cm'), ('4 cm', '4 cm'), ('5 cm', '5 cm'), ('6 cm', '6 cm')], max_length=255, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_epidurio_technique_subrecords', to=settings.AUTH_USER_MODEL)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opal.Episode')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_epidurio_technique_subrecords', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(opal.models.UpdatesFromDictMixin, opal.models.ToDictMixin, models.Model),
        ),
    ]
