# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-20 16:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import opal.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('opal', '0034_auto_20171214_1845'),
        ('epidurio', '0019_auto_20180220_1332'),
    ]

    operations = [
        migrations.CreateModel(
            name='EpiduralLocal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EpiduralOpiate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NeuroaxialDrugs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('consistency_token', models.CharField(max_length=8)),
                ('spinal_opiate_dose', models.PositiveIntegerField()),
                ('spinal_local_anaesthetic_volume', models.PositiveIntegerField()),
                ('epidural_opiate_dose', models.PositiveIntegerField()),
                ('epidural_local_anaesthetic_volume', models.PositiveIntegerField()),
                ('spinal_opiate_ft', models.CharField(blank=True, default=b'', max_length=255, null=True)),
                ('local_anaesthetic_spinal_ft', models.CharField(blank=True, default=b'', max_length=255, null=True)),
                ('epidural_opiate_ft', models.CharField(blank=True, default=b'', max_length=255, null=True)),
                ('local_anaesthetic_epidural_ft', models.CharField(blank=True, default=b'', max_length=255, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_epidurio_neuroaxialdrugs_subrecords', to=settings.AUTH_USER_MODEL)),
                ('epidural_opiate_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='epidurio.EpiduralOpiate')),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opal.Episode')),
                ('local_anaesthetic_epidural_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='epidurio.EpiduralLocal')),
            ],
            options={
                'abstract': False,
            },
            bases=(opal.models.UpdatesFromDictMixin, opal.models.ToDictMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SpinalLocal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SpinalOpiate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='technique',
            name='catheter_length_in_epidural_space',
            field=models.CharField(blank=True, choices=[('2 cm', '2 cm'), ('3 cm', '3 cm'), ('4 cm', '4 cm'), ('5 cm', '5 cm'), ('6 cm', '6 cm')], default=3, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='neuroaxialdrugs',
            name='local_anaesthetic_spinal_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='epidurio.SpinalLocal'),
        ),
        migrations.AddField(
            model_name='neuroaxialdrugs',
            name='spinal_opiate_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='epidurio.SpinalOpiate'),
        ),
        migrations.AddField(
            model_name='neuroaxialdrugs',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_epidurio_neuroaxialdrugs_subrecords', to=settings.AUTH_USER_MODEL),
        ),
    ]
