# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-20 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epidurio', '0020_auto_20180220_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neuroaxialdrugs',
            name='epidural_local_anaesthetic_volume',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='neuroaxialdrugs',
            name='epidural_opiate_dose',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='neuroaxialdrugs',
            name='spinal_local_anaesthetic_volume',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='neuroaxialdrugs',
            name='spinal_opiate_dose',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
