# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-20 17:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import opal.models


class Migration(migrations.Migration):

    dependencies = [
        ('opal', '0034_auto_20171214_1845'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('epidurio', '0021_auto_20180220_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcedureNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('consistency_token', models.CharField(max_length=8)),
                ('difficulty', models.CharField(blank=True, choices=[('Sitting', 'Sitting'), ('Lateral', 'Lateral')], max_length=255, null=True)),
                ('parasthesia', models.CharField(blank=True, choices=[('Spinal Needle', 'Spinal Needle'), ('Tuohy Needle', 'Tuohy Needle'), ('Epidural Catheter', 'Epidural Catheter')], max_length=255, null=True)),
                ('complications', models.CharField(blank=True, choices=[('None', 'None'), ('Blood in catheter', 'Blood in catheter'), ('Dural Puncture', 'Dural Puncture'), ('CSF aspirated', 'CSF aspirated'), ('Bony Obstruction', 'Bony Obstruction'), ('>1 interspace', '>1 interspace')], max_length=255, null=True)),
                ('notes', models.TextField(null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_epidurio_procedurenotes_subrecords', to=settings.AUTH_USER_MODEL)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opal.Episode')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_epidurio_procedurenotes_subrecords', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(opal.models.UpdatesFromDictMixin, opal.models.ToDictMixin, models.Model),
        ),
        migrations.AddField(
            model_name='epiduralinsertion',
            name='cervical_dilation',
            field=models.CharField(blank=True, choices=[('<2 cm', '<2 cm'), ('3-5 cm', '3-5 cm'), ('> 6 cm', '> 6 cm')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='epiduralinsertion',
            name='performed_by',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='epiduralinsertion',
            name='supervised_by',
            field=models.TextField(null=True),
        ),
    ]
