# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-21 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epidurio', '0022_auto_20180220_1743'),
    ]

    operations = [
        migrations.RenameField(
            model_name='epiduralinsertion',
            old_name='insertion_record_fk',
            new_name='Procedure_fk',
        ),
        migrations.RenameField(
            model_name='epiduralinsertion',
            old_name='insertion_record_ft',
            new_name='Procedure_ft',
        ),
        migrations.AlterField(
            model_name='epiduralinsertion',
            name='performed_by',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='epiduralinsertion',
            name='supervised_by',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='neuroaxialdrugs',
            name='epidural_local_anaesthetic_volume',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='neuroaxialdrugs',
            name='epidural_opiate_dose',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='neuroaxialdrugs',
            name='spinal_local_anaesthetic_volume',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='neuroaxialdrugs',
            name='spinal_opiate_dose',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='procedurenotes',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('Straightforward', 'Straightforward'), ('Moderately Difficult', 'Moderately Difficult'), ('Difficult', 'Difficult')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='procedurenotes',
            name='parasthesia',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('Spinal Needle', 'Spinal Needle'), ('Tuohy Needle', 'Tuohy Needle'), ('Epidural Catheter', 'Epidural Catheter')], max_length=255, null=True),
        ),
    ]
