# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-21 15:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epidurio', '0023_auto_20180221_1519'),
    ]

    operations = [
        migrations.RenameField(
            model_name='epiduralinsertion',
            old_name='Procedure_fk',
            new_name='procedure_fk',
        ),
        migrations.RenameField(
            model_name='epiduralinsertion',
            old_name='Procedure_ft',
            new_name='procedure_ft',
        ),
    ]
