# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-21 20:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epidurio', '0023_auto_20180221_2022'),
        ('epidurio', '0024_auto_20180221_1529'),
    ]

    operations = [
    ]
