# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-22 13:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import opal.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('opal', '0034_auto_20171214_1845'),
        ('epidurio', '0028_auto_20180221_2321'),
    ]

    operations = [
        migrations.CreateModel(
            name='NeuraxialDrugs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('consistency_token', models.CharField(max_length=8)),
                ('spinal_opiate_dose', models.PositiveIntegerField(blank=True, null=True)),
                ('spinal_local_anaesthetic_volume', models.PositiveIntegerField(blank=True, null=True)),
                ('epidural_opiate_dose', models.PositiveIntegerField(blank=True, null=True)),
                ('epidural_local_anaesthetic_volume', models.PositiveIntegerField(blank=True, null=True)),
                ('local_anaesthetic_spinal_ft', models.CharField(blank=True, default=b'', max_length=255, null=True)),
                ('epidural_opiate_ft', models.CharField(blank=True, default=b'', max_length=255, null=True)),
                ('spinal_opiate_ft', models.CharField(blank=True, default=b'', max_length=255, null=True)),
                ('local_anaesthetic_epidural_ft', models.CharField(blank=True, default=b'', max_length=255, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_epidurio_neuraxialdrugs_subrecords', to=settings.AUTH_USER_MODEL)),
                ('epidural_opiate_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='epidurio.EpiduralOpiate')),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opal.Episode')),
                ('local_anaesthetic_epidural_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='epidurio.EpiduralLocal')),
                ('local_anaesthetic_spinal_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='epidurio.SpinalLocal')),
                ('spinal_opiate_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='epidurio.SpinalOpiate')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_epidurio_neuraxialdrugs_subrecords', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(opal.models.UpdatesFromDictMixin, opal.models.ToDictMixin, models.Model),
        ),
        migrations.RemoveField(
            model_name='neuroaxialdrugs',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='neuroaxialdrugs',
            name='epidural_opiate_fk',
        ),
        migrations.RemoveField(
            model_name='neuroaxialdrugs',
            name='episode',
        ),
        migrations.RemoveField(
            model_name='neuroaxialdrugs',
            name='local_anaesthetic_epidural_fk',
        ),
        migrations.RemoveField(
            model_name='neuroaxialdrugs',
            name='local_anaesthetic_spinal_fk',
        ),
        migrations.RemoveField(
            model_name='neuroaxialdrugs',
            name='spinal_opiate_fk',
        ),
        migrations.RemoveField(
            model_name='neuroaxialdrugs',
            name='updated_by',
        ),
        migrations.RenameField(
            model_name='procedurenotes',
            old_name='parasthesia',
            new_name='paraesthesia',
        ),
        migrations.RemoveField(
            model_name='procedurenotes',
            name='complications',
        ),
        migrations.AddField(
            model_name='procedurenotes',
            name='complication_blood_in_catheter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='procedurenotes',
            name='complication_bony_obstruction',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='procedurenotes',
            name='complication_csf_aspirated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='procedurenotes',
            name='complication_dural_puncture',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='procedurenotes',
            name='complication_morethanone_interspace',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='procedurenotes',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='NeuroaxialDrugs',
        ),
    ]
