# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-23 21:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import opal.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('opal', '0034_auto_20171214_1845'),
        ('epidurio', '0029_auto_20180222_1303'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pregnancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('consistency_token', models.CharField(max_length=8)),
                ('parity', models.CharField(blank=True, choices=[('Primiparous', 'Primiparous'), ('Multiparous', 'Multiparous')], max_length=255, null=True)),
                ('low_risk', models.BooleanField(default=False)),
                ('platelet_count', models.CharField(help_text="Patient's latest Platelet count", max_length=20, null=True)),
                ('anticoagulants', models.BooleanField(default=False, help_text="Is the patient currently taking anticolagulants, antiplatelet agents, or any other medication that 'thins' blood or affects coagulation?")),
                ('hypertension', models.BooleanField(default=False, help_text='Does the patient have pregnancy-induced hypertension (PIH)?')),
                ('sepsis', models.BooleanField(default=False, help_text='Does the patient have signs of maternal sepsis?')),
                ('history', models.TextField(help_text='Focused summary of the relevant history. Use this area to let the amaesthetist know about any relevant hazards ar special circumstances', null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_epidurio_pregnancy_subrecords', to=settings.AUTH_USER_MODEL)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opal.Episode')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_epidurio_pregnancy_subrecords', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(opal.models.UpdatesFromDictMixin, opal.models.ToDictMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Preparation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('consistency_token', models.CharField(max_length=8)),
                ('cannula_in_situ', models.BooleanField(default=False, help_text='Does the patient have a peripheral venous cannula in situ?')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_epidurio_preparation_subrecords', to=settings.AUTH_USER_MODEL)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opal.Episode')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_epidurio_preparation_subrecords', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(opal.models.UpdatesFromDictMixin, opal.models.ToDictMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('consistency_token', models.CharField(max_length=8)),
                ('cervical_dilation', models.PositiveIntegerField()),
                ('synto_infusion', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_epidurio_progress_subrecords', to=settings.AUTH_USER_MODEL)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opal.Episode')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_epidurio_progress_subrecords', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(opal.models.UpdatesFromDictMixin, opal.models.ToDictMixin, models.Model),
        ),
        migrations.RemoveField(
            model_name='epiduralinsertion',
            name='cervical_dilation',
        ),
        migrations.RemoveField(
            model_name='epiduralrequest',
            name='anticoagulants',
        ),
        migrations.RemoveField(
            model_name='epiduralrequest',
            name='cannula_in_situ',
        ),
        migrations.RemoveField(
            model_name='epiduralrequest',
            name='history',
        ),
        migrations.RemoveField(
            model_name='epiduralrequest',
            name='hypertension',
        ),
        migrations.RemoveField(
            model_name='epiduralrequest',
            name='platelet_count',
        ),
        migrations.RemoveField(
            model_name='epiduralrequest',
            name='pyrexia',
        ),
    ]
