# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-23 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epidurio', '0030_auto_20180223_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='cervical_dilation',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
