# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-25 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epidurio', '0031_auto_20180223_2147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='epiduralfollowup',
            name='has_not_passed_urine',
        ),
        migrations.AddField(
            model_name='epiduralfollowup',
            name='general_anaesthesia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='epiduralfollowup',
            name='itu_admission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='epiduralfollowup',
            name='other',
            field=models.TextField(null=True),
        ),
    ]
