# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-25 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epidurio', '0033_epiduralfollowup_has_not_passed_urine'),
    ]

    operations = [
        migrations.AddField(
            model_name='epiduralfollowup',
            name='home_before_follow_up',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='epiduralfollowup',
            name='performed_by',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='epiduralfollowup',
            name='post_natal_appointment_required',
            field=models.BooleanField(default=False),
        ),
    ]
