# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-27 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epidurio', '0034_auto_20180225_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregnancy',
            name='history',
            field=models.TextField(help_text='Focused summary of the relevant history. Use this area to let the anaesthetist know about any relevant hazards or special circumstances', null=True),
        ),
        migrations.AlterField(
            model_name='progress',
            name='cervical_dilation',
            field=models.PositiveIntegerField(help_text='Cervical dilatation as at last examination', null=True),
        ),
        migrations.AlterField(
            model_name='progress',
            name='synto_infusion',
            field=models.BooleanField(default=False, help_text='Syntocinon infusion?'),
        ),
    ]
