# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-21 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epidurio', '0035_auto_20180227_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigation',
            name='rhinovirus',
            field=models.CharField(blank=True, choices=[('pending', 'pending'), ('positive', 'positive'), ('negative', 'negative')], max_length=20),
        ),
    ]
